### PR TITLE
Fix deprecation warnings on Windows/DMD 2.070.

### PR DESCRIPTION
**Pull request by s-ludwig**

### CODE REVIEW

**Comment by s-ludwig** [comment]
NVM, just saw #30

**Comment by repeatedly** [comment]
Can #30 use your way without breaking old versions?

**Comment by s-ludwig** [comment]
Should work without issues. BTW, that `else version (Win64)` branch there can be removed altogether AFAICS (`Windows` will also be defined anyway), which is why I haven't touched it.

**Comment by CyberShadow** [comment]
I would probably merge this over #30 (seeing as there's no one to merge #30) :)

**Pull request closed without merging**
