### PR TITLE
Remove checked-in C headers

### PR DESCRIPTION
**Pull request by Geod24**
Now that the bindings support multiple versions,
having checked-in headers doesn't make much sense.

### CODE REVIEW

**Comment by CyberShadow** [comment]
On one hand, I would say that they're useful because you can just use `git grep` to a symbol's name to see both the C and D declaration next to each other, which is helpful to quickly check if a declaration was translated correctly. So, if anything, we ought to check in the C headers of supported versions.

On the other hand, if we are to support version *ranges* instead of discrete versions, then that indeed doesn't make much sense.

**Comment by Geod24** [comment]
OpenSSL still had a Semver-esque approach, in that all letters in the `v1.1.1[letter]`  branch were binary compatible (they had to be to be distributable as `.so`).

So in reality, we support:
- 1.0.2x
- 1.1.0x
- 1.1.1x
- 3.x.x

1.0.2 and 1.1.0 are actually recommended against on the OpenSSL website, but there are still systems using it (Buildkite, apparently, much to my dismay, uses 1.0.2).

As much as I love `git grep` (my personal code even uses `T funcName (params)` for decl / def and `funcName(args)` to make it easy to grep for decls), using it with 4 supported versions (I think if we go this way, it'd make sense to check in the latest version of every release) would add a lot of noises, because you'd have at least 4 hits on the header files, and up to 4 on the D side.

On the other hand, while working on improving those bindings, the most useful source was actually the `git` history of `openssl/openssl`, which allowed me to see what change was made, when, under which rationale... So proving correctness nowadays is much more likely to involve the same work as adding them require (which is why I've been adding links to commits on Github to make such work easier in the future).

**Comment by CyberShadow** [comment]
> As much as I love `git grep` (my personal code even uses `T funcName (params)` for decl / def and `funcName(args)` to make it easy to grep for decls), using it with 4 supported versions (I think if we go this way, it'd make sense to check in the latest version of every release) would add a lot of noises, because you'd have at least 4 hits on the header files, and up to 4 on the D side.

Regarding specifically this observation, I think that's perfectly fine and a good thing, you'll be able to effortlessly see if any declarations changed across versions, implying the possible need of a `version` block on the D side.

One more hypothetical advantage of keeping headers in this repository is that when a new version of the targeted project comes out, any updates to these bindings would be accompanied by a check-in of the new version of the targeted library's headers. Review would then consist of checking if the diff of the two is equivalent. Although one can supply the link to the GitHub diff of the original project, that diff would also contain implementation details, which is not needed to review changes in D bindings. I say this is a hypothetical advantage because we currently don't fully target any OpenSSL version, but perhaps one day this will hold.

Overall I think it boils down to personal preference / established workflow, and I can't think of any strong objective arguments one way or the other. Since this is a Deimos repository, I would generally lean towards sticking to the process described on https://wiki.dlang.org/Deimos, but we've already deviated from it due to targeting multiple versions...

**Comment by Geod24** [comment]
> Regarding specifically this observation, I think that's perfectly fine and a good thing, you'll be able to effortlessly see if any declarations changed across versions, implying the possible need of a `version` block on the D side.

In my experience, many definitions are multi lines, so you can't really get that picture "at a glance".

> Overall I think it boils down to personal preference / established workflow, and I can't think of any strong objective arguments one way or the other.

Agreed, I don't have a strong preference here, just didn't think it was making much sense, but I'll close the PR.

>  I would generally lean towards sticking to the process described on [...]

I think this process hasn't been updated in years, and we have enough evidence that it doesn't quite work.

**Comment by CyberShadow** [comment]
> In my experience, many definitions are multi lines, so you can't really get that picture "at a glance".

You can with `-A` / `-B` / `-C`, or an editor integration that allows jumping between hits while keeping the matched line on the same place on the screen.

> I think this process hasn't been updated in years, and we have enough evidence that it doesn't quite work.

I think the process makes sense (I wrote most of that article so I'm biased here) but not all repositories follow it, nor were they consistent to begin with when the article was created. It was mostly aimed to guide new efforts, to prevent things getting even more inconsistent than they already are.

We can certainly discuss the contents of that page if you're up for it.

**Pull request closed without merging**
